"""add ticker_state

Revision ID: 8477ee6f8ae2
Revises: 341aa1a8ef69
Create Date: 2026-07-18 05:06:23.958600

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '8477ee6f8ae2'
down_revision: Union[str, None] = '341aa1a8ef69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ticker_state',
    sa.Column('exchange', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('instrument', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('underlying', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expiry', sa.DateTime(timezone=True), nullable=False),
    sa.Column('strike', sa.Float(), nullable=False),
    sa.Column('option_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bid_price', sa.Float(), nullable=True),
    sa.Column('bid_size', sa.Float(), nullable=True),
    sa.Column('ask_price', sa.Float(), nullable=True),
    sa.Column('ask_size', sa.Float(), nullable=True),
    sa.Column('underlying_price', sa.Float(), nullable=True),
    sa.Column('taker_fee_rate', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('exchange', 'instrument')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticker_state')
    # ### end Alembic commands ###
