"""add_balances_json_to_exchange_state

Revision ID: a6f0281b121d
Revises: 8477ee6f8ae2
Create Date: 2026-07-20 22:45:49.097094

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "a6f0281b121d"
down_revision: str | None = "8477ee6f8ae2"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "exchange_state", sa.Column("balances", sa.JSON(), server_default="{}", nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("exchange_state", "balances")
    # ### end Alembic commands ###
