"""initial schema

Revision ID: b5c114583a03
Revises:
Create Date: 2026-07-14 16:50:31.226992

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = "b5c114583a03"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("level", sa.Enum("INFO", "WARN", "ERROR", name="alertlevel"), nullable=False),
        sa.Column("channel", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("message", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sent_at", sa.DateTime(), nullable=False),
        sa.Column("meta", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_alerts_level"), "alerts", ["level"], unique=False)
    op.create_index(op.f("ix_alerts_sent_at"), "alerts", ["sent_at"], unique=False)
    op.create_table(
        "book_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("exchange", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("instrument", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("ts", sa.DateTime(), nullable=False),
        sa.Column("bids_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("asks_json", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_book_snapshots_exchange"), "book_snapshots", ["exchange"], unique=False
    )
    op.create_index(
        op.f("ix_book_snapshots_instrument"), "book_snapshots", ["instrument"], unique=False
    )
    op.create_index(op.f("ix_book_snapshots_ts"), "book_snapshots", ["ts"], unique=False)
    op.create_table(
        "exchange_state",
        sa.Column("exchange", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("balance_usd", sa.Float(), nullable=False),
        sa.Column("margin_used_usd", sa.Float(), nullable=False),
        sa.Column(
            "ws_status",
            sa.Enum("CONNECTED", "RECONNECTING", "UNHEALTHY", name="wsstatus"),
            nullable=False,
        ),
        sa.Column(
            "rest_status", sa.Enum("OK", "RATE_LIMITED", "DOWN", name="reststatus"), nullable=False
        ),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("exchange"),
    )
    op.create_table(
        "opportunities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("detected_at", sa.DateTime(), nullable=False),
        sa.Column("mode", sa.Enum("LIVE", "PAPER", "BACKTEST", name="mode"), nullable=False),
        sa.Column("instrument", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("symbol", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("expiry", sa.DateTime(), nullable=False),
        sa.Column("strike", sa.Float(), nullable=False),
        sa.Column("option_type", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("buy_from", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sell_to", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("top_ask", sa.Float(), nullable=False),
        sa.Column("top_bid", sa.Float(), nullable=False),
        sa.Column("walked_ask", sa.Float(), nullable=True),
        sa.Column("walked_bid", sa.Float(), nullable=True),
        sa.Column("walked_size", sa.Float(), nullable=True),
        sa.Column("spread_pct", sa.Float(), nullable=False),
        sa.Column("apr_pct", sa.Float(), nullable=False),
        sa.Column("max_notional_usd", sa.Float(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING", "APPROVED", "REJECTED", "EXECUTED", "EXPIRED", name="opportunitystatus"
            ),
            nullable=False,
        ),
        sa.Column("rejection_reason", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_opportunities_detected_at"), "opportunities", ["detected_at"], unique=False
    )
    op.create_index(
        op.f("ix_opportunities_instrument"), "opportunities", ["instrument"], unique=False
    )
    op.create_index(op.f("ix_opportunities_status"), "opportunities", ["status"], unique=False)
    op.create_index(op.f("ix_opportunities_symbol"), "opportunities", ["symbol"], unique=False)
    op.create_table(
        "positions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("exchange", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("instrument", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("size", sa.Float(), nullable=False),
        sa.Column("avg_price", sa.Float(), nullable=False),
        sa.Column("opened_at", sa.DateTime(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_positions_exchange"), "positions", ["exchange"], unique=False)
    op.create_index(op.f("ix_positions_instrument"), "positions", ["instrument"], unique=False)
    op.create_table(
        "trades",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("opportunity_id", sa.Integer(), nullable=False),
        sa.Column("opened_at", sa.DateTime(), nullable=False),
        sa.Column("closed_at", sa.DateTime(), nullable=True),
        sa.Column("mode", sa.Enum("LIVE", "PAPER", "BACKTEST", name="mode"), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PLACING",
                "LEG1_FILLED",
                "LEG2_FILLED",
                "FILLED",
                "HEDGING",
                "HEDGED",
                "STUCK",
                "FAILED",
                name="tradestatus",
            ),
            nullable=False,
        ),
        sa.Column("buy_exchange", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("sell_exchange", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("requested_size", sa.Float(), nullable=False),
        sa.Column("buy_fill_price", sa.Float(), nullable=True),
        sa.Column("buy_fill_size", sa.Float(), nullable=True),
        sa.Column("sell_fill_price", sa.Float(), nullable=True),
        sa.Column("sell_fill_size", sa.Float(), nullable=True),
        sa.Column("net_pnl_usd", sa.Float(), nullable=True),
        sa.Column("slippage_pct", sa.Float(), nullable=True),
        sa.Column("fees_usd", sa.Float(), nullable=True),
        sa.Column("error", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_trades_opened_at"), "trades", ["opened_at"], unique=False)
    op.create_index(op.f("ix_trades_opportunity_id"), "trades", ["opportunity_id"], unique=False)
    op.create_index(op.f("ix_trades_status"), "trades", ["status"], unique=False)
    op.create_table(
        "orders",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("trade_id", sa.Integer(), nullable=False),
        sa.Column("exchange", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("side", sa.Enum("BUY", "SELL", name="side"), nullable=False),
        sa.Column("kind", sa.Enum("IOC_LIMIT", "MARKET_OUT", name="orderkind"), nullable=False),
        sa.Column("requested_price", sa.Float(), nullable=False),
        sa.Column("requested_size", sa.Float(), nullable=False),
        sa.Column("filled_price", sa.Float(), nullable=True),
        sa.Column("filled_size", sa.Float(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("PLACING", "FILLED", "PARTIAL", "REJECTED", "CANCELLED", name="orderstatus"),
            nullable=False,
        ),
        sa.Column("exchange_order_id", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("placed_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("raw_response", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.ForeignKeyConstraint(
            ["trade_id"],
            ["trades.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_orders_trade_id"), "orders", ["trade_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_orders_trade_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_trades_status"), table_name="trades")
    op.drop_index(op.f("ix_trades_opportunity_id"), table_name="trades")
    op.drop_index(op.f("ix_trades_opened_at"), table_name="trades")
    op.drop_table("trades")
    op.drop_index(op.f("ix_positions_instrument"), table_name="positions")
    op.drop_index(op.f("ix_positions_exchange"), table_name="positions")
    op.drop_table("positions")
    op.drop_index(op.f("ix_opportunities_symbol"), table_name="opportunities")
    op.drop_index(op.f("ix_opportunities_status"), table_name="opportunities")
    op.drop_index(op.f("ix_opportunities_instrument"), table_name="opportunities")
    op.drop_index(op.f("ix_opportunities_detected_at"), table_name="opportunities")
    op.drop_table("opportunities")
    op.drop_table("exchange_state")
    op.drop_index(op.f("ix_book_snapshots_ts"), table_name="book_snapshots")
    op.drop_index(op.f("ix_book_snapshots_instrument"), table_name="book_snapshots")
    op.drop_index(op.f("ix_book_snapshots_exchange"), table_name="book_snapshots")
    op.drop_table("book_snapshots")
    op.drop_index(op.f("ix_alerts_sent_at"), table_name="alerts")
    op.drop_index(op.f("ix_alerts_level"), table_name="alerts")
    op.drop_table("alerts")
    # ### end Alembic commands ###
